import type { Metadata } from 'next'
import clsx from 'clsx'
import { Inter } from 'next/font/google'
import '@/assets/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'text-slate-900')}>{children}
        <div id="modals"></div>
      </body>
    </html>
  )
}
